### ISSUE TITLE
I get error code 500 when enabling the extension

### ISSUE THREAD

**Issue by K4LCIFER** [pe1uca/xExtension-RateLimiter#1]
When I try to enable the extension from the extensions page in my FreshRSS instance, I get the following error:
![image](https://github.com/user-attachments/assets/9bac9057-ea47-4c91-a541-69d1beb89e03)

Compose:
```yaml
version: "2.4"

volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
      - ./config.custom.php:/var/www/FreshRSS/data/config.custom.php
      - ./config-user.custom.php:/var/www/FreshRSS/data/config-user.custom.php
    ports:
      - "8080:80"
    environment:
      CRON_MIN: '*/10'
```
FreshRSS is on v1.25.0.
